// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdmc0YE5OmMbEbEn9pvio_BNAmg_TPBaI',
    appId: '1:412893091737:web:5197c2d48ad25a22dc2508',
    messagingSenderId: '412893091737',
    projectId: 'pushnotification-ac3d9',
    authDomain: 'pushnotification-ac3d9.firebaseapp.com',
    storageBucket: 'pushnotification-ac3d9.appspot.com',
    measurementId: 'G-GS5E13VE33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2y1VbVILu5_jPhpOd3jsc36jPK8NJtok',
    appId: '1:412893091737:android:8d0c55a3f7ec5ec8dc2508',
    messagingSenderId: '412893091737',
    projectId: 'pushnotification-ac3d9',
    storageBucket: 'pushnotification-ac3d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2zjq4gw32hyFVaIuAv5Xx7uTcKw9yZko',
    appId: '1:412893091737:ios:a2a832029c40d8afdc2508',
    messagingSenderId: '412893091737',
    projectId: 'pushnotification-ac3d9',
    storageBucket: 'pushnotification-ac3d9.appspot.com',
    androidClientId: '412893091737-eg826r3rshp75r0di9jhcslcd9u9fi30.apps.googleusercontent.com',
    iosClientId: '412893091737-veof6fg0hrrvja6qi61sj3me5mcjhhas.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFlutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2zjq4gw32hyFVaIuAv5Xx7uTcKw9yZko',
    appId: '1:412893091737:ios:a2a832029c40d8afdc2508',
    messagingSenderId: '412893091737',
    projectId: 'pushnotification-ac3d9',
    storageBucket: 'pushnotification-ac3d9.appspot.com',
    androidClientId: '412893091737-eg826r3rshp75r0di9jhcslcd9u9fi30.apps.googleusercontent.com',
    iosClientId: '412893091737-veof6fg0hrrvja6qi61sj3me5mcjhhas.apps.googleusercontent.com',
    iosBundleId: 'com.example.simpleFlutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdmc0YE5OmMbEbEn9pvio_BNAmg_TPBaI',
    appId: '1:412893091737:web:68daa934a94cc1dadc2508',
    messagingSenderId: '412893091737',
    projectId: 'pushnotification-ac3d9',
    authDomain: 'pushnotification-ac3d9.firebaseapp.com',
    storageBucket: 'pushnotification-ac3d9.appspot.com',
    measurementId: 'G-VKWCPQ1DG8',
  );

}